version: 2

sources:
    - name: staging
      database: dezoomcamp-2025-450707
      schema: trips_data_all

      tables:
          - name: green_tripdata
          - name: yellow_tripdata
          - name: fhv_tripdata
